### PR TITLE
Update to prevent filtered variants being ignored

### PR DESCRIPTION
**Pull request by andyb3**
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_happy/30)

### CODE REVIEW

**Review by aledj2 — COMMENTED** [review]
looks ok, but do the different happy arguments  need explaining in the readme?

> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_happy/30#-:-LQdk8or372Ss0T4ljUQ:b-9ejapv)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @NMNS93, @woook, @aledj2, and @Graeme-Smith)

**Review by andyb3 — COMMENTED** [review]
Have added updated the README

> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_happy/30#-:-LR7Xnj4-YXBcJ1XXCZh:bncl5sl)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @aledj2, @NMNS93, @woook, and @Graeme-Smith)

___
*[src/code.sh, line 59 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_happy/30#-LR7XEEw2mZ1VwZGu4Rx:-LR7XEEw2mZ1VwZGu4Ry:b-5w6tgr) ([raw file](https://github.com/moka-guys/dnanexus_happy/blob/f37273ae83fca5ba62e4ed51820dc93ddc9c5260/src/code.sh#L59)):*
> ```Shell
> #Run hap.py in docker container
> #The options used are based on those used when running the precisionFDA GA4GH Benchmarking in vcfeval-partial-credit mode, with gender as female (i.e. NA12878)
> #and Adjust confident regions as False (in the README on the precisionFDA app it warns that this option can cause non-confident calls to slip back into confident region)
> ```

Turns out that Adjust conf regions is on by default, even if the `--adjust-conf-regions` argument is not given. Since this is on by default, I spoke to Wook and we decided to leave it on rather than switching it off.

**Review by aledj2 — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_happy/30)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @aledj2, @NMNS93, @woook, and @Graeme-Smith)

**Review by aledj2 — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_happy/30#-:-LR7vuiZ1LAEW5Fpht_x:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @NMNS93, @woook, and @Graeme-Smith)

**Pull request merged**
