### PR TITLE
Produce ga4gh summary report HTML

### PR DESCRIPTION
**Pull request by andyb3**
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_happy/26)

### CODE REVIEW

**Comment by AmyAmelia** [comment]
+@amyamelia 

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_happy/26#-:-LBV0RN70Q_tEgZEe0TO:b-z3lu1q)*

**Comment by AmyAmelia** [comment]
Reviewed 3 of 5 files at r1.
Review status: 3 of 5 files reviewed at latest revision, all discussions resolved.

---

*[ga4gh_rep.py/Dockerfile, line 4 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_happy/26#-LBV2CZ75OgTWSee58Dh:-LBV2CZ75OgTWSee58Di:b-s94h90) ([raw file](https://github.com/moka-guys/dnanexus_happy/blob/c950200a098dbc519a9fd3fc6f01637e5ef60b99/ga4gh_rep.py/Dockerfile#L4)):*
> ```Dockerfile
> ## Used to produce HTML report based on output from Illumina hap.py
> ## See https://github.com/ga4gh/benchmarking-tools/tree/master/reporting/basic
> ```

Might be worth referencing the use case example on Dockerhub.
Expand on comments of what this code does ie. produces the Docker image for HTML report 

---

*[src/code.sh, line 74 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_happy/26#-LBV3drA5W0MnYPnPsD-:-LBV3drA5W0MnYPnPsD0:bcux84y) ([raw file](https://github.com/moka-guys/dnanexus_happy/blob/c950200a098dbc519a9fd3fc6f01637e5ef60b99/src/code.sh#L74)):*
> ```Shell
> fi
> 
> # Generate summary_report
> ```

Is this the html generation?

---


*Comments from [Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_happy/26)*

**Comment by andyb3** [comment]
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[ga4gh_rep.py/Dockerfile, line 4 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_happy/26#-LBV2CZ75OgTWSee58Dh:-LBVD0CzCQCYg4DErbZg:b-896fix) ([raw file](https://github.com/moka-guys/dnanexus_happy/blob/c950200a098dbc519a9fd3fc6f01637e5ef60b99/ga4gh_rep.py/Dockerfile#L4)):*
<details><summary><i>Previously, AmyAmelia wrote…</i></summary><blockquote>

Might be worth referencing the use case example on Dockerhub.
Expand on comments of what this code does ie. produces the Docker image for HTML report 
</blockquote></details>

Done.

---

*[src/code.sh, line 74 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_happy/26#-LBV3drA5W0MnYPnPsD-:-LBVDL2C-CGJFpLsYkI6:b-896fix) ([raw file](https://github.com/moka-guys/dnanexus_happy/blob/c950200a098dbc519a9fd3fc6f01637e5ef60b99/src/code.sh#L74)):*
<details><summary><i>Previously, AmyAmelia wrote…</i></summary><blockquote>

Is this the html generation?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_happy/26)*

**Comment by AmyAmelia** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_happy/26#-:-LBVEoCX3fIndztQ9cw1:bnfp4nl)*

**Pull request merged**
